edition = "2021"
unstable_features = true

condense_wildcard_suffixes = true
fn_params_layout = "Tall"
force_explicit_abi = true
format_code_in_doc_comments = true
format_macro_matchers = true
hard_tabs = false
imports_granularity = "Crate"
max_width = 100
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
